model:
  pretrained_model_path: "src/weights/Qwen2.5-0.5B-Instruct"
  device: "cuda"
  dtype: "bfloat16"
  preload_ckpt_file: "ckpt_000100.pt"
data:
  path: "Countdown-Tasks-3to4/data"
  test_size: 128
rewards:
  format: 0.1
  answer: 1.0
training:
  random_seed: 1337
  max_prompt_len: 256
  max_gen_len: 512
  batch_size: 256
  num_questions_per_batch: 32
  # Number of examples per gradient accumulation step
  micro_batch_size: 2
  max_grad_norm: 1.0
  learning_rate: 1.0e-5
  weight_decay: 0.0
  betas: [0.9, 0.999]
  ckpt_dir: "src/ckpt"
  log_dir: "logs"
  skip_unfinished_instances: true
  ckpt_save_interval: 100
  eval_interval: 10
  # save GPU memory by offloading the optimizer states to CPU
  memory_efficient_adamw: true